on:
  manual:
  release:
    types: [created]

name: Handle Release

jobs:
  generate:
    strategy: 
      matrix:
        target: 
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: 386
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: arm

    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Build
        run: 
          - make setup
          - GOOS=${{ matrix.target.goos }} GOARCH=${{ matrix.target.goarch }} make build
             
      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/* 
