on:
  workflow_dispatch:
  release:
    types: [created]

name: Handle Release

jobs:
  generate:
    strategy: 
      matrix:
        target: 
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: 386
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: arm

    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.21.1' # The Go version to download (if necessary) and use.
      - name: Build
        env: 
          GOOS: ${{ matrix.target.goos }} 
          GOARCH: ${{ matrix.target.goarch }}
        run: |
          make setup
          make build
             
      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/* 
